[workspace]
resolver = "2"

members = ["rs/algorithm", "rs/data-intake", "rs/data-processing", "rs/shared"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.80"
chrono = {version = "0.4.35"}
dotenv = "0.15.0"
fluvio = {version = "0.23.1", default-features = false}
futures-util = "0.3.30"
rocket = {version = "0.5.0-rc.3", features = ["json"]}
rstest = "0.22.0"
rustls = "0.23.12"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.114"
sqlx = "0.8.0"
thiserror = "1.0"
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
uuid = {version = "1.8.0", features = ["v4"]}
