[workspace]
resolver = "2"

members = ["rs/data-intake", "rs/data-processing", "rs/shared"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
fluvio = {version = "0.23.1", default-features = false}
serde = {version = "1.0", features = ["derive"]}
sqlx = "0.7.4"
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
uuid = {version = "1.8.0", features = ["v4"]}
