[workspace]
resolver = "2"

members = ["rs/data-intake", "rs/shared"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
serde = {version = "1.0", features = ["derive"]}
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
