[package]
edition.workspace = true
name = "algorithm"
version = "0.1.0"

[dependencies]
rstest = {workspace = true}
shared = {path = "../shared"}
thiserror = {workspace = true}
tracing = {workspace = true}
