[package]
edition.workspace = true
name = "algorithm"
version = "0.1.0"

[dependencies]
rstest = {workspace = true}
shared = {workspace = true}
thiserror = {workspace = true}
tracing = {workspace = true}
uuid = {workspace = true}
