[package]
edition = "2021"
name = "data-intake"
version = "0.1.0"

[[bin]]
name = "data-intake"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.80"
dotenv = "0.15.0"
greptimedb-ingester = {git = "https://github.com/GreptimeTeam/greptimedb-ingester-rust.git", rev = "2e6b0c5eb6a5e7549c3100e4d356b07d15cce66d"}
jsonwebtoken = {version = "9.3", default-features = false}
multipart = "0.18.0"
rand = "0.8.5"
reqwest = {version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
]}
rocket = {version = "0.5.0-rc.3", features = ["json"]}
rstest = "0.18.2"
rustls = "0.23"
serde = {version = "1.0", features = ["derive"]}
serde_json = {workspace = true}
shared = {path = "../shared"}
tokio = "1.36.0"
tracing = "0.1.40"
tracing-subscriber = {version = "0.3.18", features = ["env-filter"]}
uuid = {workspace = true}
