[package]
edition = "2021"
name = "data-intake"
version = "0.1.0"

[[bin]]
name = "data-intake"
path = "src/main.rs"

[dependencies]
dotenv = {workspace = true}
greptimedb-ingester = {git = "https://github.com/GreptimeTeam/greptimedb-ingester-rust.git", rev = "2e6b0c5eb6a5e7549c3100e4d356b07d15cce66d"}
jsonwebtoken = {version = "9.3", default-features = false}
multipart = "0.18.0"
rand = "0.8.5"
reqwest = {version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
]}
rocket = {workspace = true}
rstest = {workspace = true}
rustls = {workspace = true}
serde_json = {workspace = true}
shared = {path = "../shared"}
tokio = {workspace = true}
tracing = {workspace = true}
