[package]
edition.workspace = true
name = "chat-backend"
version = "0.2.0"

[dependencies]
rocket = {workspace = true}
rstest = {workspace = true}
shared = {workspace = true}
thiserror = {workspace = true}
tokio = {workspace = true}
tracing = {workspace = true}
