[package]
edition.workspace = true
name = "log-classification"
version = "0.1.0"

[dependencies]
rstest = {workspace = true}
serde_json = {workspace = true}
shared = {path = "../shared"}
thiserror = {workspace = true}
tracing = {workspace = true}
