name: CI

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login
        run: echo "${{ secrets.HIK8S_BOT_GHCR_WRITE_TOKEN }}" | docker login ghcr.io -u hik8s --password-stdin
      
      - name: Docker Build
        run: |
          IMAGES=("data-intake" "data-processing" "data-vectorizer" "prompt-engine" "chat-backend")
          for IMAGE in "${IMAGES[@]}"; do
            docker build --target $IMAGE --tag $IMAGE .
          done

      - name: Docker Tag and Push
        run: |
          REGISTRY='ghcr.io/hik8s'
          IMAGES=("data-intake" "data-processing" "data-vectorizer" "prompt-engine" "chat-backend")
          for IMAGE in "${IMAGES[@]}"; do
            VERSION=$(grep -E 'version = "[^"]*"$' rs/$IMAGE/Cargo.toml | awk -F\" '{print $2}')
            docker tag $IMAGE $REGISTRY/$IMAGE:$VERSION
            docker push $REGISTRY/$IMAGE:$VERSION
          done
